#!/bin/sh
#
# Copyright (c) 2016 Nest Labs, Inc.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


die() {
	echo " *** fatal error $*"
	exit 1
}

export NO_PUSH=1

set -x

TAG=`git describe --abbrev=0 --match="[0123456789].[0123456789][0123456789].[0123456789][0123456789]" master`
[ -n "$TAG" ] || TAG=`git describe --abbrev=0 --match="[0123456789].[0123456789][0123456789].[0123456789][0123456789]*" master`

[ -n "$TAG" ] || die "Can't calculate latest release"

OTHER_TAG="`git tag -l "[0123456789].[0123456789][0123456789].[0123456789][0123456789]" --sort=v:refname | xargs -n 1 git describe --exact-match | tail -n 1`"

[ "$TAG" == "$OTHER_TAG" ] || OTHER_TAG="`git tag -l "[0123456789].[0123456789][0123456789].[0123456789][0123456789]*" --sort=v:refname | xargs -n 1 git describe --exact-match | tail -n 1`"
[ "$TAG" == "$OTHER_TAG" ] || die "Can't reconcile '$TAG' and '$OTHER_TAG'. Is 'master' up to date?"

echo "Helping for release $TAG"

./update-full-tag-for-release "$TAG" || die

./update-latest-release "$TAG" || die

./update-doxygen-gh-pages || die

