#!/bin/sh
#
# Copyright (c) 2016 Nest Labs, Inc.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


die() {
	echo fatal error $*
	exit -1
}

set -x

[ -d proj ] && rm -fr proj

git fetch origin gh-pages

git clone .git proj || die
cd proj || die

git checkout full/latest-release || die

REV=`git describe --tags --always`

./configure || die

doxygen doxygen.cfg
rm -fr doc/latex

git add doc -f || die
git stash || die
git clean -f -d -x || die
git checkout gh-pages || die
git rm -fr doc
git stash pop || die

if git status --porcelain 2>/dev/null | grep -e '^[RMDA]' -e '^?[RDMA]' >/dev/null
then
	git commit -m "doxygen: Rebuild from $REV

Based-on: `git rev-parse $REV`" || die
	git push origin gh-pages || die
	cd .. || die
	rm -fr proj || die
else
	echo "No changes."
	cd .. || die
	rm -fr proj || die
	exit 0
fi
[ -n "${NO_PUSH}" ] && exit 0

read -p "Press enter to push." || exit 0

git push origin gh-pages || die
