#!/bin/sh
#
# Copyright (c) 2016 Nest Labs, Inc.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


die() {
	echo fatal error $*
	exit -1
}

set -x

REMOTE=${REMOTE-origin}

BASE="$1"

[ -n "$BASE" ] || BASE="master"

git fetch ${REMOTE} autoconf/${BASE}:autoconf/${BASE} full/${BASE}:full/${BASE}

#git branch -f autoconf/${BASE} ${REMOTE}/autoconf/${BASE} || die
#git branch -f full/${BASE} ${REMOTE}/full/${BASE} || die

./update-autoconf ${BASE} autoconf/${BASE} full/${BASE} || die

git branch -f autoconf/${BASE} __AUTOCONF_HEAD || die
git branch -f full/${BASE} __FULL_HEAD || die

git branch -D __AUTOCONF_HEAD
git branch -D __FULL_HEAD

[ -n "${NO_PUSH}" ] && exit 0

read -p "Press enter to push." || exit 0

git push ${REMOTE} autoconf/${BASE}:autoconf/${BASE} full/${BASE}:full/${BASE} || die

