#!/bin/sh
#
# Copyright (c) 2016 Nest Labs, Inc.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


die() {
	echo fatal error $*
	exit -1
}

set -x

REF="$1"

[ -n "$REF" ] || die "missing argument (needs a ref)"

BASE="$2"

[ -n "$BASE" ] || BASE=`git rev-parse --verify "full/$(git describe --abbrev=0 --match="[0123456789].[0123456789][0123456789].[0123456789][0123456789]" ${REF}^)^2"`
[ -n "$BASE" ] || BASE=`git rev-parse --verify "full/$(git describe --abbrev=0 --match="[0123456789].[0123456789][0123456789].[0123456789][0123456789]*" ${REF}^)^2"`

[ -n "$BASE" ] || BASE="autoconf/master"

echo "Using '${BASE}' as the autoconf base"

NOTEFILE="`mktemp -t $(basename $0)`"

git cat-file -p "$(git rev-parse --verify ${REF})" | tail -n +6 | awk 'BEGIN {f=1} /^-----[A-Z ]*-----$/ {f=!f} f' | sed '/^-----[A-Z ]*-----$/d' > "${NOTEFILE}" || die

cat "${NOTEFILE}"

./update-autoconf "$REF" "$BASE"

[ -d proj ] && rm -fr proj

git clone .git proj || die

cd proj || die

git checkout "${REF}" || die

git merge -m "release: Merge built autotools files" --no-edit origin/__AUTOCONF_HEAD || die

git tag -f --file="${NOTEFILE}" -s "full/${REF}" || die

git push -f origin "full/${REF}" || die

cd .. || die

rm -fr proj || die

git branch -D __AUTOCONF_HEAD

rm -fr "${NOTEFILE}"

[ -n "${NO_PUSH}" ] && exit 0

read -p "Press enter to push." || exit 0

git push origin "full/${REF}" || die

