#!/bin/sh
#
# Copyright (c) 2016 Nest Labs, Inc.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


die() {
	echo " *** Fatal error: $*"
	exit -1
}

set -x

REF="$1"

[ -n "$REF" ] || die "missing argument (needs a ref)"

BASE="$2"

[ -n "$BASE" ] || BASE="autoconf/master"

[ -d proj ] && { chmod -R 777 proj && rm -fr proj ; }

git clone .git proj || die

cd proj || die

git checkout "${REF}" || die

REV=`git describe --tags --always`

./bootstrap.sh --all || die

find . -name autom4te.cache -print0 | xargs -0 rm -fr || die

git add . -f || die
git stash || die
git checkout "${BASE}" || git checkout -b "${BASE}" autoconf/master || die
git rm . -f -r
git stash pop || die

if git status --porcelain 2>/dev/null | grep -e '^[RMDA]' -e '^?[RDMA]' >/dev/null
then
	git commit -m "build-system: Autotools rebuild from $REV

Based-on: `git rev-parse $REV`" || die
else
	echo "No changes."
fi

git push -f origin "${BASE}":refs/heads/__AUTOCONF_HEAD || die

cd .. || die

rm -fr proj || die

