# File automatically generated by autoandr 0.00.01
# "src/ipc-dbus" - Wed Oct 26 13:04:57 PDT 2016
#

LOCAL_PATH := $(call my-dir)

#### BEGIN libwpantund-dbus ####
include $(CLEAR_VARS)
LOCAL_MODULE := libwpantund-dbus
LOCAL_MODULE_TAGS := eng
LOCAL_CPPFLAGS += -DHAVE_CONFIG_H
LOCAL_CPPFLAGS += -Wno-c++11-narrowing
LOCAL_CPPFLAGS += -Wno-date-time
LOCAL_CPPFLAGS += -Wno-non-virtual-dtor
LOCAL_CPPFLAGS += -Wno-unused-parameter
LOCAL_CPPFLAGS += -fexceptions
LOCAL_CPPFLAGS += -frtti
LOCAL_C_INCLUDES += $(LOCAL_PATH)/.
LOCAL_C_INCLUDES += $(LOCAL_PATH)/..
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src/ipc-dbus
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src/util
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src/wpantund
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/assert-macros
LOCAL_C_INCLUDES += external/boost
LOCAL_C_INCLUDES += external/dbus
LOCAL_SRC_FILES += ../../../../src/ipc-dbus/DBUSIPCServer.cpp
LOCAL_SRC_FILES += ../../../../src/ipc-dbus/DBusIPCAPI_v0.cpp
LOCAL_SRC_FILES += ../../../../src/ipc-dbus/DBusIPCAPI_v1.cpp
LOCAL_SRC_FILES += ../../../../src/util/DBUSHelpers.cpp
include $(BUILD_STATIC_LIBRARY)
#### END libwpantund-dbus ####
