# File automatically generated by autoandr 0.00.01
# "src" - Wed Oct 19 15:20:21 PDT 2016
#

LOCAL_PATH := $(call my-dir)
include $(NDK_PROJECT_PATH)/etc/android/src/wpanctl/Android.mk
include $(NDK_PROJECT_PATH)/etc/android/src/ipc-dbus/Android.mk
include $(NDK_PROJECT_PATH)/etc/android/src/ncp-spinel/Android.mk
include $(NDK_PROJECT_PATH)/etc/android/src/wpantund/Android.mk
