#!/bin/sh
#
# Copyright (c) 2018 Nest Labs, Inc.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

die()
{
    echo " *** ERROR: " $*
    exit 1
}

install_packages_apt()
{
    # apt update and install dependencies
    sudo apt-get update || die

    sudo apt-get -y install dbus || die
    sudo apt-get -y install gcc g++ libdbus-1-dev || die
    sudo apt-get -y install autoconf-archive || die
    sudo apt-get -y install bsdtar || die
    sudo apt-get -y install libtool || die
    sudo apt-get -y install libglib2.0-dev || die
}

install_packages_opkg()
{
    echo 'opkg not supported currently' && false
}

install_packages_rpm()
{
    echo 'rpm not supported currently' && false
}

install_packages_brew()
{
    echo 'brew not supported currently' && false
}

install_packages_source()
{
    echo 'source not supported currently' && false
}

install_packages()
{
    PM=source
    if which apt-get; then
        PM=apt
    elif which rpm; then
        PM=rpm
    elif which opkg; then
        PM=opkg
    elif which brew; then
        PM=brew
    fi
    install_packages_$PM
}

main()
{
    install_packages
}

main
