#!/bin/sh
#
# Copyright (c) 2016 Nest Labs, Inc.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


die() {
	echo " *** fatal error $*"
	exit 1
}

set -x

TAG="`git tag -l "[0123456789].[0123456789][0123456789].[0123456789][0123456789]" --sort=v:refname | xargs -n 1 git describe --exact-match | tail -n 1`"

[ -n "$TAG" ] || TAG="`git tag -l "[0123456789].[0123456789][0123456789].[0123456789][0123456789]*" --sort=v:refname | xargs -n 1 git describe --exact-match | tail -n 1`"

[ -n "$TAG" ] || die "Can't calculate latest release"

echo "Tag '${TAG}' seems to be the new latest-release."

git tag -f latest-release "${TAG}" || die

FULL_TAG=`git tag -l "full/${TAG}" --sort=v:refname | xargs -n 1 git describe --exact-match | tail -n 1`

[ -n "$FULL_TAG" ] || die "No full tag"

echo "Tag '${FULL_TAG}' seems to be the new full/latest-release."

git tag -f full/latest-release "${FULL_TAG}" || die

[ -n "${NO_PUSH}" ] && exit 0

read -p "Press enter to push." || exit 0

git push -f origin latest-release full/latest-release || die

